# Generated by Django 3.2.3 on 2021-06-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='UserProfile/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='創建使用者')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='BookCover/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('ISBN', models.CharField(max_length=255, verbose_name='ISBN')),
                ('author', models.CharField(default='', max_length=255)),
                ('publisher', models.CharField(max_length=255, verbose_name='publisher')),
                ('rating', models.IntegerField(verbose_name='評分')),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='創建時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='創建時間')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.review', verbose_name='評論')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='創建使用者')),
            ],
        ),
    ]
