# Generated by Django 3.2.3 on 2021-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_comment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
